name: PyPI

on:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
{%- if cookiecutter.publish_to_pypi == "y" %}
  PUBLISH_TO_PYPI: true
{%- else %}
  PUBLISH_TO_PYPI: false
{% endif %}

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Python Version from File
        id: python_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v4
        with:
          python-version: {% raw %}${{ steps.python_version.outputs.version }}{% endraw %}

      - name: Install Dependencies
        run: make install

      - name: Build Wheel
        run: make build

      # This will only run on Tags
      - name: Publish package
        if: {% raw %}${{ env.PUBLISH_TO_PYPI == 'true' }} && github.event_name == 'push' && startsWith(github.ref, 'refs/tags'){% endraw %}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: {% raw %}${{ secrets.PYPI_PUBLISH_API_KEY }}{% endraw %}
